spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/escuela?serverTimezone=UTC
    username: root
    password: admin   
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-cursos
  mvc:
      pathmatch:
        matching-strategy: ant-path-matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
      instance-id: instancia1
server:
  port: 8080 
