
spring:
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    application:
        name: servicio-formacion
server:
    port: 9000
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        #register-with-eureka: false